const express= require("express")
const routes = express.Router()
const controller = require("../controllers/controller")
const photo = require("../multer/photo")
const passport = require("passport")
routes.get("/dashboard",controller.home)
routes.get("/pages/tables",passport.isAuth,controller.tables)
routes.get("/pages/profile",passport.isAuth,controller.profile)
routes.get("/",controller.signin)
routes.get("/pages/sign-up",controller.signup)
routes.get("/pages/tables/delete/:id",controller.deleteUser)
routes.get("/pages/update",passport.isAuth,photo,controller.updateUser)
routes.post("/insertdata",passport.isAuth,photo,controller.insertData)
routes.post("/updatedata",photo,controller.updatedata)
routes.get("/logout",controller.logout)
routes.get("/pages/myinfo",passport.isAuth,controller.myinfo)
routes.get("/pages/changepass",passport.isAuth,controller.changepass)
routes.post("/changepassword",controller.changepassword)
routes.post("/signindata",passport.authenticate("local", {failureRedirect:'/'}),controller.signindata)
routes.get("/forgotpass",controller.forgotpass)
routes.get("/otp",controller.otp)
routes.post("/forgotpass",controller.forgotpassword)

// zzxc
module.exports = routes